### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by clove040** [c-yn/FSNet#12]
请问下载好的数据集地址放在哪里

**Comment by c-yn** [comment]
可以按照如下方式放置数据集，把reside-indoor放在你的某一目录下面，然后修改main.py里面的数据集地址即可。
├──reside-indoor
     ├──train
          ├──gt
          └──hazy
     └──test
          ├──gt
          └──hazy
└──reside-outdoor
     ├──train
          ├──gt
          └──hazy
     └──test
          ├──gt
          └──hazy

**Comment by clove040** [comment]
很感激您的回复，但是很抱歉由于我刚学习这方面知识，在main.py中没有找到数据集地址，拜托您能告诉我在哪一行修改吗，真的真的感谢！

**Comment by c-yn** [comment]
运行程序的时候 将your_path换成你自己的地址即可
--data_dir your_path/reside-indoor

**Comment by clove040** [comment]
谢谢你！

**Comment by clove040** [comment]
请问哥测试的模型有百度网盘链接吗

**Comment by c-yn** [comment]
链接：https://pan.baidu.com/s/1oLr95zvKuSk673oDKcq6Nw?pwd=s3su 
提取码：s3su

**Comment by clove040** [comment]
非常感谢作者！

**Comment by clove040** [comment]
作者你好，请问训练好的模型怎么处理别的图片呢？

**Comment by clove040** [comment]
不好意思再次打扰了，请问您有reside-outdoor的百度网盘链接吗

**Comment by c-yn** [comment]
处理别的图片更换数据集地址即可，如果没有gt，可以把降质图片复制一份当作gt，相当更改dataload中gt的地址即可。
ots地址
链接：https://pan.baidu.com/s/1jmib-wPIoj7ICZoHehmhwg?pwd=w2zi 
提取码：w2zi

**Comment by clove040** [comment]
谢谢哥，对我一个初学者来说哥的回复真的帮助很多！

**Comment by clove040** [comment]
请问哥你们训练室外数据集时用的是哪一部分呢，因为我只做了室内数据集的训练，导致处理室外图片时效果很差，

**Comment by clove040** [comment]
请问哥你们训练室外数据集时用的是哪一部分呢，因为我只做了室内数据集的训练，导致处理室外图片时效果很差，

**Comment by c-yn** [comment]
室外用的30多W张的那个数据集
