### ISSUE TITLE
Somethings about Data preprocessing.Files in this Path of your project:Dehaze/ITS/data/data_load.py

### ISSUE THREAD

**Issue by Urian-oy** [c-yn/FSNet#13]
Why did you choose to crop the image to 256*256 size instead of resize?THANKS

**Comment by c-yn** [comment]
Hi, we did this following previous methods.
I think cropping is more reasonable for dense tasks to maintain the original data distribution than the resize operation.
Anyway, you could have a try by resizing images to 256*256 for training.
