### ISSUE TITLE
About Haze4K trained weight

### ISSUE THREAD

**Issue by WWJ0720** [c-yn/FSNet#5]
Could you please provide the test result and weights of Haze4K? Thank you so much！！

**Comment by c-yn** [comment]
Hi, we uploaded the test results in the link. However, the pre-trained model is missing. You can obtain the reported scores by training following our setup. 
If you have trouble reproducing our results, please let us know. Thanks.

**Comment by WWJ0720** [comment]
> Hi, we uploaded the test results in the link. However, the pre-trained model is missing. You can obtain the reported scores by training following our setup. If you have trouble reproducing our results, please let us know. Thanks.

Thank you so much！
