### ISSUE TITLE
在训练ITS时，loss几个epoch后就变成nan

### ISSUE THREAD

**Issue by dauing** [c-yn/FSNet#9]

**Comment by renjianyanhuo** [comment]
你好，请问成功复现了嘛

**Comment by c-yn** [comment]
不知道其他人是否遇到过类似的问题，我一开始训练的时候是正常的。

**Comment by renjianyanhuo** [comment]
你好，是否方便加个微信交流：C1907401030




1907401031
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "c-yn/FSNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月3日(星期二) 凌晨4:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [c-yn/FSNet] 在训练ITS时，loss几个epoch后就变成nan (Issue #9)





 
不知道其他人是否遇到过类似的问题，我一开始训练的时候是正常的。

**Comment by LaughingHH** [comment]
我笑了
